### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by Shinmera** [Shinmera/foss-governance#1]
Sup dawgs.

If you have any complaints or questions or whatnot I think this would be one of the fastest ways to get correspondence. Email might be a bit less convenient, probably.

**Comment by Shinmera** [comment]
Due to severe restrictions in the capabilities of BibTeX, I've decided to switch over to BibLaTeX. The usage of the actual commands should be the same. However, it is much more capable than the BibTeX system. Most notably, it adds support for a variety of rather important tags in the bib files, such as `url`.

In order to compile a fully formatted version of the document, the required steps are now as follows:
1. `luatex foss-governance.tex`
2. `biber foss-governance.tex`
3. `luatex foss-governance.tex`

Your editor should hopefully have native support for BibLaTeX and Biber. If not, have a look at [ShareLaTeX](https://www.sharelatex.com/) which does offer this capability.

I've also created a separate bib file for each of the major sections, so that we can edit the files in tandem without stepping over each other's feet.

**Comment by Shinmera** [comment]
I finished my draft on the section about Linux. It is a bit long (~1100 words) so you could probably also get away with writing less than that in your own section. Keep it around 800-900 words, I'd say. We'll still need some room in the end for the last two sections.

**Comment by Shinmera** [comment]
There's a missing reference to "Clang in Xcode". Please fix it as soon as possible.

**Comment by Shinmera** [comment]
I have finished the last two sections of the paper now. Doing a primitive word count excluding the glossary, we are now at just below 5'500 words. Given that the count is an overestimation, I think we should be just about in the right area in terms of length.

Please have another read through and correct any minor mistakes or grammar problems you might find in your respective parts. If you have feedback about the last two sections of the document, let me know.

Otherwise, once the missing reference is fixed, I think this paper should be about finished and ready to be sent off to the prof. Before we do that though, make sure that the slides accompanying the document are as they should be for the coming presentation on Monday.

Once you are certain that everything is in order, including the presentation, please let me know and I'll send everything off to the professor.

**Comment by Fluci** [comment]
Thanks a lot! I'm busy this evening, hope it's ok if I go through everything tomorrow afternoon.

**Comment by dvicini** [comment]
Same here, I am very busy today (meeting until 7, after that I have to finish up some other stuff), but tomorrow I hope to be able to fix everything.

**Comment by Shinmera** [comment]
Sure, works for me. I'm currently editing the slides around a bit, making them look a bit better, etc.

**Comment by Shinmera** [comment]
@Fluci Can you get this done asap?

**Comment by Fluci** [comment]
Done, can be sent. Sorry for the delay.
